version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "s3-logs-extension-demo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1sth4z1hda355"
s3_prefix = "s3-logs-extension-demo"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
